name: API

on: [push, pull_request]

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cypress install
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          start: npm cypress run
          browser: chrome